### ISSUE TITLE
Add link for new review to hit page after hit has been accepted

### ISSUE THREAD

**Issue by zihel** [turkopticon/turkoptiscript#2]
originally posted at turkopticon/turkopticon-rails-app#38

> I just had to return a hit that was turning out to be too long. The requester is new (no reviews on either TO site) and the the link on the hit page disappeared once I'd accepted the hit. I had to use the "new review" page, which took time because I had to locate all the needed data for the fields. I don't know if it's possible to keep the link there after the hit is accepted, but if it is that would save time; I had to copy/paste the data for the fields from several different sources.

**Comment by zihel** [comment]
@kimadagem The script doesn't add anything to the 'accepted HIT' page because the requester ID is not available there. It will only be on pages where it can find a requester ID.

I know it's extremely inconvenient, but perhaps the best solution is just to remember to look in your HIT queue before you return it.

**Comment by kimadagem** [comment]
Thank you for the suggestion. I rarely use the queue so I didn't know there was a way to access the info there. I forgot to try it today, hopefully I'll remember tomorrow.
