### ISSUE TITLE
Hit title not displaying correctly on "add review" page; symbol missing

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkoptiscript#4]
This is what it looked like right after I used the script:
![to2 hit title symbol weirdness](https://cloud.githubusercontent.com/assets/26679556/25291959/24d96bd0-26a2-11e7-8d02-cdc46e6063bd.jpg)

This is what it looked like after I copy/pasted the correct title into that field:
![to2 hit title symbol weirdness fixed](https://cloud.githubusercontent.com/assets/26679556/25291992/45ebf946-26a2-11e7-8ca3-a023a5663c87.jpg)

I don't recall seeing this issue before but I may have missed it.

**Comment by zihel** [comment]
Related to #3; root cause is the same.
